export const CREATE_DOCUMENT_REQUEST = 'CREATE_DOCUMENT_REQUEST'
export const CREATE_DOCUMENT_SUCCESS = 'CREATE_DOCUMENT_SUCCESS'
export const CREATE_DOCUMENT_FAILURE = 'CREATE_DOCUMENT_FAILURE'

export const SET_IPFS_UPLOAD_PROGRESS = 'SET_IPFS_UPLOAD_PROGRESS'
export const SET_ENCRYPTING_FILE_PROGRESS = 'SET_ENCRYPTING_FILE_PROGRESS'
export const SET_IS_IPFS_READY = 'SET_IS_IPFS_READY'
